apiVersion: v1
kind: Pod
metadata:
  namespace: croc-hunter
  name: croc-hunter
  labels:
    app: croc-hunter
spec:
  containers:
    - name: croc-hunter
      image: quay.io/lachie83/croc-hunter
      ports:
        - containerPort: 8080
      readinessProbe:
        httpGet:
          path: /
          port: 8080